
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# SMTP notification
notify: !include gmail_config.yaml

eufy: !include eufy.yaml
      
# nest: !include nest_config.yaml
  
google_assistant: !include google_assistant.yaml

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  
# downloader:
#   download_dir: downloads

# sensor:
#   - platform: dht
#     sensor: DHT11
#     pin: 4
#     monitored_conditions:
#       - temperature
#       - humidity

template:
###### to call weather forecast service to get hourly into a new entity Dec 2023 #####
  - trigger:
      - platform: time_pattern
        hours: "/1"
    action:
      - service: weather.get_forecasts
        data:
          type: hourly
        target:
          entity_id: weather.huis
        response_variable: hourly
    sensor:
      - name: Weather Forecast Hourly
        unique_id: weather_forecast_hourly
        icon: mdi:weather-cloudy-clock
        state: "{{ now().isoformat() }}"
        attributes:
          forecast: "{{ hourly['weather.huis']['forecast'] }}"
