project_id: gassist-261119
service_account:
    private_key: !secret google_assistant_pkey
    client_email: !secret google_assistant_email
report_state: true
exposed_domains:
    - switch
    - cover
entity_config:
    switch.adguard_filtering:
        expose: false
    switch.adguard_parental_control:
        expose: false
    switch.adguard_protection:
        expose: false
    switch.adguard_safe_browsing:
        expose: false
    switch.adguard_safe_search:
        expose: false
    switch.lamp:
        expose: false