  - name: gmail
    platform: smtp
    server: smtp.live.com
    port: 587
    timeout: 15
    sender: !secret email_outlook
    encryption: starttls
    username: !secret email_outlook
    password: !secret outlook_token
    recipient:
      - !secret email_gmail2
      - !secret email_hotmail
    sender_name: My Home Assistant
  - name: hotmail
    platform: smtp
    server: smtp.live.com
    port: 587
    timeout: 15
    sender: !secret email_outlook
    encryption: starttls
    username: !secret email_outlook
    password: !secret outlook_token
    recipient:
      - !secret email_hotmail
    sender_name: My Home Assistant