substitutions:
  device_name: emon
  pin_set_delay: 1s
  component_update_delay: 450ms
  update_time: 8s # must be > (pin_set_delay+component_update_delay*2) * channels
  ct_update_time: never
  ic1Volts: '230'
  # filters
  intoZero: '0.0005' # '0.00049'
  # known load in Amps (known Watts / Volts)
  known125w: '0.544'
  known900w: '3.913'
  known2300w: '10.0'
  known3300w: '14.348'
  known6000w: '26.09'
  # value in logs
  logs125w: '0.005' # '0.0085', '0.0035', 0.00134'
  logs900w: '0.009' # '0.006', 0.0055'
  logs2300w: '0.0157' # '0.01'
  logs3300w: '0.022' # '0.023', '0.025'
  logs6000w: '0.045' # '0.047'

esphome:
  name: ${device_name}
  compile_process_limit: 1

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret emon_static_ip
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret emon_fallback_ssid
    password: !secret emon_fallback_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

# Enable Web server.
web_server:
  port: 80

# Enable logging
logger:

captive_portal:

# Time used for daily KWh usage
time:
  - platform: homeassistant
    id: homeassistant_time


#.......................................
#...Below script sets up PIN A and B ...
#......then tells CT# to update.........
#.......................................

interval:
  - interval: ${update_time}
    then:
      - script.execute: readCTs

script:
  - id: readCTs
    then:
      # A	B  CT
      # 0	0  1
      # 0	1  2
      # 1	0  3
      # 1	1  4
      # setup for CT1 A=0 B=0 - ct1Amps
      # - output.turn_off: pinA
      # - output.turn_off: pinB
      # - delay: ${pin_set_delay}
      # - component.update: ct1Amps
      # - delay: ${component_update_delay}
      # - component.update: ct1Watts
      # - delay: ${component_update_delay}
      # setup for CT2 A=0 B=1 - ct2Amps
      - output.turn_off: pinA
      - output.turn_on: pinB
      - delay: ${pin_set_delay}
      - component.update: ct2Amps
      - delay: ${component_update_delay}
      - component.update: ct2Watts
      - delay: ${component_update_delay}
      # setup for CT3 A=1 B=0 - ct3Amps
      - output.turn_on: pinA
      - output.turn_off: pinB
      - delay: ${pin_set_delay}
      - component.update: ct3Amps
      - delay: ${component_update_delay}
      - component.update: ct3Watts
      - delay: ${component_update_delay}
      # setup for CT4 A=1 B=1 - ct4Amps
      - output.turn_on: pinA
      - output.turn_on: pinB
      - delay: ${pin_set_delay}
      - component.update: ct4Amps
      - delay: ${component_update_delay}
      - component.update: ct4Watts
      - delay: ${component_update_delay}
      # Update Washing Watts after all individual updates
      - lambda: id(update_washing_watts).execute();

  - id: update_washing_watts
    mode: queued
    then:
      - lambda: |-
          if (isnan(id(plug0Power).state)) {
            ESP_LOGD("main", "plug0Power state is NaN");
            id(washingWatts).publish_state(0.0);
          } else {
            float power = id(plug0Power).state;
            ESP_LOGD("main", "plug0Power: %.2f", power);
            id(washingWatts).publish_state(power > 0.0 ? power : 0.0);
          }

  - id: update_ctGrossWatts
    mode: queued
    then:
      - lambda: |-
          float gross_watts = id(ct2Watts).state + id(ct3Watts).state + id(ct4Watts).state + id(washingWatts).state;
          ESP_LOGD("custom", "Updating Gross Watts: ct2Watts=%.2f, ct3Watts=%.2f, ct4Watts=%.2f, washingWatts=%.2f, total=%.2f",
                   id(ct2Watts).state, id(ct3Watts).state, id(ct4Watts).state, id(washingWatts).state, gross_watts);
          id(grossWatts_sensor).publish_state(gross_watts);

  - id: update_ctNetWatts
    mode: queued
    then:
      - lambda: |-
          float net_watts = id(grossWatts_sensor).state - (isnan(id(haos_sbfspot_sma_ac_power).state) ? 0.0 : id(haos_sbfspot_sma_ac_power).state);
          float netWatts = net_watts > 0.0 ? net_watts : 0.0;
          ESP_LOGD("custom", "Updating Net Watts: grossWatts=%.2f, solarWatts=%.2f, total=%.2f",
                   id(grossWatts_sensor).state, id(haos_sbfspot_sma_ac_power).state, netWatts);
          id(netWatts_sensor).publish_state(netWatts);

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${device_name} IP Address
      disabled_by_default: true
  - platform: homeassistant
    name: ${device_name} HAOS-SBFspot SMA Timestamp
    id: haos_sbfspot_sma_timestamp
    entity_id: sensor.haos_sbfspot_sma_timestamp
    icon: mdi:clock-digital

output:
  - platform: gpio
    pin: D1
    id: pinB
  - platform: gpio
    pin: D2
    id: pinA

sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Signal
    update_interval: 60s
  - platform: uptime
    name: ${device_name} Uptime
    unit_of_measurement: days
    update_interval: 300s
    accuracy_decimals: 2
    filters:
      - multiply: 0.000011574
    id: Uptime

  - platform: template
    name: Gross Watts
    id: grossWatts_sensor
    unit_of_measurement: W
    accuracy_decimals: 1
    device_class: power
    icon: mdi:flash
    state_class: measurement
    update_interval: never
  - platform: template
    name: Net Watts
    id: netWatts_sensor
    unit_of_measurement: W
    accuracy_decimals: 1
    device_class: power
    icon: mdi:flash
    state_class: measurement
    update_interval: never

  - platform: adc
    pin: A0
    id: adc_sensor
    update_interval: ${update_time}
  #    attenuation: 11db #esp32 only

  # smart plug
  # Washing
  - platform: homeassistant
    id: plug0Power
    entity_id: sensor.smart_plug_current_power
    on_value:
      then:
        - lambda: |-
            ESP_LOGD("main", "Executing update_washing_watts script");
            id(update_washing_watts).execute();
        - lambda: |-
            ESP_LOGD("main", "Executing update_ctGrossWatts script");
            id(update_ctGrossWatts).execute();
        - lambda: |-
            ESP_LOGD("main", "Executing update_ctNetWatts script");
            id(update_ctNetWatts).execute();


  # solar
  - platform: homeassistant
    name: ${device_name} HAOS-SBFspot SMA AC Power
    id: haos_sbfspot_sma_ac_power
    entity_id: sensor.haos_sbfspot_sma_ac_power
    state_class: measurement
    unit_of_measurement: W
    device_class: power
    icon: mdi:solar-power-variant

  #Apms
  # Channel 2: EV
  - platform: ct_clamp
    sensor: adc_sensor
    name: ${device_name} ct2Amps, EV
    id: ct2Amps
    unit_of_measurement: A
    device_class: current
    accuracy_decimals: 5
    sample_duration: 200ms
    update_interval: ${ct_update_time}
    filters:
      - calibrate_linear:
          - ${intoZero} -> 0.0
          - ${logs125w} -> ${known125w}
          - ${logs900w} -> ${known900w}
          - ${logs2300w} -> ${known2300w}
          - ${logs3300w} -> ${known3300w}
          - ${logs6000w} -> ${known6000w}
      # filter less than 920W, equates no power throughput
      - lambda: |-
          if (x > 4) return x;
          else return 0;
    # When Current updates, update Watts
    on_value:
      then:
        - sensor.template.publish:
            id: ct2Watts
            state: !lambda 'return isnan(id(ct2Amps).state) ? 0.0 : id(ct2Amps).state * ${ic1Volts};'
        - lambda: id(update_ctGrossWatts).execute();
        - lambda: id(update_ctNetWatts).execute();

  # Channel 3: Dryer
  - platform: ct_clamp
    sensor: adc_sensor
    name: ${device_name} ct3Amps, dryer
    id: ct3Amps
    unit_of_measurement: A
    device_class: current
    accuracy_decimals: 5
    sample_duration: 200ms
    update_interval: ${ct_update_time}
    filters:
      - calibrate_linear:
          - ${intoZero} -> 0
          - ${logs2300w} -> ${known2300w}
      # filter less than 920W, equates no power throughput
      - lambda: |-
          if (x > 4) return x;
          else return 0;
    # When Current updates, update Watts
    on_value:
      then:
        - sensor.template.publish:
            id: ct3Watts
            state: !lambda 'return isnan(id(ct3Amps).state) ? 0.0 : id(ct3Amps).state * ${ic1Volts};'
        - lambda: id(update_ctGrossWatts).execute();
        - lambda: id(update_ctNetWatts).execute();

  # Channel 4: House
  - platform: ct_clamp
    sensor: adc_sensor
    name: ${device_name} ct4Amps, house
    id: ct4Amps
    unit_of_measurement: A
    device_class: current
    accuracy_decimals: 5
    sample_duration: 200ms
    update_interval: ${ct_update_time}
    filters:
      - calibrate_linear:
          - ${intoZero} -> 0.0
          - ${logs125w} -> ${known125w}
          - ${logs900w} -> ${known900w}
          - ${logs2300w} -> ${known2300w}
          - ${logs3300w} -> ${known3300w}
          - ${logs6000w} -> ${known6000w}
      # filter nagative
      - lambda: |-
          if (x > 0) return x;
          else return 0;
    # When Current updates, update Watts
    on_value:
      then:
        - sensor.template.publish:
            id: ct4Watts
            state: !lambda |-
              float house_amps = id(ct4Amps).state;
              ESP_LOGD("main", "ct4Amps: %.5f", house_amps);
              float house_watts = isnan(house_amps) ? 0.0 : house_amps * ${ic1Volts};
              ESP_LOGD("main", "House Watts: %.2f", house_watts);
              float ct3_watts = id(ct3Watts).state;
              ESP_LOGD("main", "ct3Watts: %.2f", ct3_watts);
              float washing_watts = id(washingWatts).state;
              ESP_LOGD("main", "Washing Watts: %.2f", washing_watts);
              float house_net_watts = house_watts - ct3_watts - washing_watts;
              ESP_LOGD("main", "House Net Watts (before check): %.2f", house_net_watts);
              house_net_watts = house_net_watts > 0.0 ? house_net_watts : 0.0;
              ESP_LOGD("main", "House Net Watts (after check): %.2f", house_net_watts);
              return house_net_watts;
        - lambda: |-
            ESP_LOGD("main", "Executing update_ctGrossWatts script");
            id(update_ctGrossWatts).execute();
        - lambda: |-
            ESP_LOGD("main", "Executing update_ctNetWatts script");
            id(update_ctNetWatts).execute();


  # Watts
  # Washing
  - platform: template
    name: ${device_name} Washing watts
    id: washingWatts
    accuracy_decimals: 0
    unit_of_measurement: W
    device_class: power
    icon: "mdi:flash-circle"
    update_interval: ${ct_update_time}
  # EV
  - platform: template
    name: ${device_name} EV watts
    id: ct2Watts
    accuracy_decimals: 0
    unit_of_measurement: W
    device_class: power
    icon: "mdi:flash-circle"
    update_interval: ${ct_update_time}
  # Dryer
  - platform: template
    name: ${device_name} Dryer watts
    id: ct3Watts
    accuracy_decimals: 0
    unit_of_measurement: W
    device_class: power
    icon: "mdi:flash-circle"
    update_interval: ${ct_update_time}
  # House
  - platform: template
    name: ${device_name} House watts
    id: ct4Watts
    accuracy_decimals: 0
    unit_of_measurement: W
    device_class: power
    icon: "mdi:flash-circle"
    update_interval: ${ct_update_time}

  # kWh
  # EV
  - platform: total_daily_energy
    name: ${device_name} Daily EV kWh
    power_id: ct2Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

  # Dryer
  - platform: total_daily_energy
    name: ${device_name} Daily Dryer kWh
    power_id: ct3Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

  # House
  - platform: total_daily_energy
    name: ${device_name} Daily House kWh
    power_id: ct4Watts
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

  # Net
  - platform: total_daily_energy
    name: ${device_name} Daily Net kWh
    power_id: netWatts_sensor
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

  # Gross
  - platform: total_daily_energy
    name: ${device_name} Daily Gross kWh
    power_id: grossWatts_sensor
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
