substitutions:
  device_name: somfy-remote

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

esphome:
  name: ${device_name}
  #platform: ESP32
  
  libraries:
    - SPI
    - EEPROM
    - SmartRC-CC1101-Driver-Lib@2.5.7
    - Somfy_Remote_Lib@0.4.1

external_components:
  - source:
      type: local
      path: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret somfy_static_ip
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret somfy_fallback_ssid
    password: !secret esp_fallback_password

captive_portal:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time
    
binary_sensor:
  - platform: status
    name: ${device_name} Status
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${device_name} IP Address
      disabled_by_default: true

# Sensors with general information.
sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Signal
    update_interval: 60s
  - platform: uptime
    name: ${device_name} Uptime
    unit_of_measurement: days
    update_interval: 300s
    accuracy_decimals: 2
    filters:
      - multiply: 0.000011574

cover:
  - platform: somfy
    name: Kitchen
    id: kitchen
    storage_key: kitchen
    remote_address: !secret somfy_address_kitchen
    pin:
      number: GPIO22

switch:
  - platform: template
    name: "PROG Kitchen"
    turn_on_action:
      - lambda: |-
          id(kitchen)->program();
